### ISSUE TITLE
auth0 error: redirect-uri parameter is not valid

### ISSUE THREAD

**Issue by saukap** [graphcool-examples/expo-auth0-instagram-example#2]
I cloned this repo and followed the steps to setup and auth0 account. I've also updated the **Allowed Callback URLs** field in the auth0 dashboard to point to my app's expo URL: 

exp://rw-prc.saukap.expo-auth0-instagram-example.exp.direct/+/redirect

However, I get this error from auth0 when I attempt to login. Before I report this to them, was wondering if you encountered this:

`The redirect_uri parameter is not valid: \"<Exponent URL without Port>/+/redirect\" If url looks fine, check that you are not including non printable chars`

**Comment by marktani** [comment]
What's the URL you entered?

**Comment by marktani** [comment]
Hm I did not encounter this issue before, but it looks like you did not enter
> exp://rw-prc.saukap.expo-auth0-instagram-example.exp.direct/+/redirect
in your Expo app but something else. Are you running this on Expo 14 or Expo 15?

**Comment by marktani** [comment]
Ah, you need to update this line with your Auth0 url: https://github.com/graphcool-examples/expo-auth0-instagram-example/blob/master/main.js#L27

**Comment by saukap** [comment]
Oops, didn't read the `README` fully. Thanks, it works now.

**Comment by marktani** [comment]
Awesome! :slightly_smiling_face:
