### ISSUE TITLE
Project description says Exponent rather than Expo

### ISSUE THREAD

**Issue by brentvatne** [graphcool-examples/expo-auth0-instagram-example#3]
<img width="761" alt="screen shot 2017-04-12 at 4 06 20 pm" src="https://cloud.githubusercontent.com/assets/90494/24977112/016a630c-1f9a-11e7-8d69-6dc5601abb1e.png">

:1st_place_medal:

**Comment by marktani** [comment]
Thanks! :raised_hands:
